"""add created_at

Revision ID: 14d0c9570ddb
Revises: 6cad0eb11289
Create Date: 2026-07-25 00:09:33.094794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14d0c9570ddb'
down_revision: Union[str, Sequence[str], None] = '6cad0eb11289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'created_at')
    # ### end Alembic commands ###
